services:
  qr_redirect_microservice_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qr_redirect_db
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: