spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5435/qr_redirect_db

  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5435/qr_redirect_db
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  data:
    redis:
      host: localhost
      port: 6379
      password: password
server:
  port: 8083
