spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://qr_redirect_microservice_db:5432/qr_redirect_db

  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://qr_redirect_microservice_db:5432/qr_redirect_db
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
  data:
    redis:
      host: qr_redis
      port: 6379
      password: password
server:
  port: 8080